/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PermitsIndexRouteImport } from './routes/permits.index'
import { Route as PermitsPermitNumberRouteImport } from './routes/permits.$permitNumber'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PermitsIndexRoute = PermitsIndexRouteImport.update({
  id: '/permits/',
  path: '/permits/',
  getParentRoute: () => rootRouteImport,
} as any)
const PermitsPermitNumberRoute = PermitsPermitNumberRouteImport.update({
  id: '/permits/$permitNumber',
  path: '/permits/$permitNumber',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/permits/$permitNumber': typeof PermitsPermitNumberRoute
  '/permits/': typeof PermitsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/permits/$permitNumber': typeof PermitsPermitNumberRoute
  '/permits': typeof PermitsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/permits/$permitNumber': typeof PermitsPermitNumberRoute
  '/permits/': typeof PermitsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/permits/$permitNumber' | '/permits/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/permits/$permitNumber' | '/permits'
  id: '__root__' | '/' | '/permits/$permitNumber' | '/permits/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PermitsPermitNumberRoute: typeof PermitsPermitNumberRoute
  PermitsIndexRoute: typeof PermitsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/permits/': {
      id: '/permits/'
      path: '/permits'
      fullPath: '/permits/'
      preLoaderRoute: typeof PermitsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/permits/$permitNumber': {
      id: '/permits/$permitNumber'
      path: '/permits/$permitNumber'
      fullPath: '/permits/$permitNumber'
      preLoaderRoute: typeof PermitsPermitNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PermitsPermitNumberRoute: PermitsPermitNumberRoute,
  PermitsIndexRoute: PermitsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
