/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApprovalsRouteImport } from './routes/approvals'
import { Route as AuditTrailRouteImport } from './routes/audit-trail'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as WorkLogsRouteImport } from './routes/work-logs'
import { Route as PermitsIndexRouteImport } from './routes/permits.index'
import { Route as PermitsPermitNumberRouteImport } from './routes/permits.$permitNumber'
import { Route as PermitsNewRouteImport } from './routes/permits.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsRoute = ApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditTrailRoute = AuditTrailRouteImport.update({
  id: '/audit-trail',
  path: '/audit-trail',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkLogsRoute = WorkLogsRouteImport.update({
  id: '/work-logs',
  path: '/work-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const PermitsIndexRoute = PermitsIndexRouteImport.update({
  id: '/permits/',
  path: '/permits/',
  getParentRoute: () => rootRouteImport,
} as any)
const PermitsPermitNumberRoute = PermitsPermitNumberRouteImport.update({
  id: '/permits/$permitNumber',
  path: '/permits/$permitNumber',
  getParentRoute: () => rootRouteImport,
} as any)
const PermitsNewRoute = PermitsNewRouteImport.update({
  id: '/permits/new',
  path: '/permits/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/audit-trail': typeof AuditTrailRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/work-logs': typeof WorkLogsRoute
  '/permits/$permitNumber': typeof PermitsPermitNumberRoute
  '/permits/new': typeof PermitsNewRoute
  '/permits/': typeof PermitsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/audit-trail': typeof AuditTrailRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/work-logs': typeof WorkLogsRoute
  '/permits/$permitNumber': typeof PermitsPermitNumberRoute
  '/permits/new': typeof PermitsNewRoute
  '/permits': typeof PermitsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/audit-trail': typeof AuditTrailRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/work-logs': typeof WorkLogsRoute
  '/permits/$permitNumber': typeof PermitsPermitNumberRoute
  '/permits/new': typeof PermitsNewRoute
  '/permits/': typeof PermitsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/approvals'
    | '/audit-trail'
    | '/login'
    | '/settings'
    | '/work-logs'
    | '/permits/$permitNumber'
    | '/permits/new'
    | '/permits/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/approvals'
    | '/audit-trail'
    | '/login'
    | '/settings'
    | '/work-logs'
    | '/permits/$permitNumber'
    | '/permits/new'
    | '/permits'
  id:
    | '__root__'
    | '/'
    | '/approvals'
    | '/audit-trail'
    | '/login'
    | '/settings'
    | '/work-logs'
    | '/permits/$permitNumber'
    | '/permits/new'
    | '/permits/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApprovalsRoute: typeof ApprovalsRoute
  AuditTrailRoute: typeof AuditTrailRoute
  LoginRoute: typeof LoginRoute
  SettingsRoute: typeof SettingsRoute
  WorkLogsRoute: typeof WorkLogsRoute
  PermitsPermitNumberRoute: typeof PermitsPermitNumberRoute
  PermitsNewRoute: typeof PermitsNewRoute
  PermitsIndexRoute: typeof PermitsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals': {
      id: '/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof ApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit-trail': {
      id: '/audit-trail'
      path: '/audit-trail'
      fullPath: '/audit-trail'
      preLoaderRoute: typeof AuditTrailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work-logs': {
      id: '/work-logs'
      path: '/work-logs'
      fullPath: '/work-logs'
      preLoaderRoute: typeof WorkLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/permits/': {
      id: '/permits/'
      path: '/permits'
      fullPath: '/permits/'
      preLoaderRoute: typeof PermitsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/permits/$permitNumber': {
      id: '/permits/$permitNumber'
      path: '/permits/$permitNumber'
      fullPath: '/permits/$permitNumber'
      preLoaderRoute: typeof PermitsPermitNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/permits/new': {
      id: '/permits/new'
      path: '/permits/new'
      fullPath: '/permits/new'
      preLoaderRoute: typeof PermitsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApprovalsRoute: ApprovalsRoute,
  AuditTrailRoute: AuditTrailRoute,
  LoginRoute: LoginRoute,
  SettingsRoute: SettingsRoute,
  WorkLogsRoute: WorkLogsRoute,
  PermitsPermitNumberRoute: PermitsPermitNumberRoute,
  PermitsNewRoute: PermitsNewRoute,
  PermitsIndexRoute: PermitsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
